language: r
sudo: required
dist: trusty
env:
  global:
  - secure: ESg+lbDrbAaziHe5fB/wHRZCHalTHFYXyamCz2fVWMnh8AtDfbrD/c+CrHXS4eXD5xwta8nQ3hCRId93VrTnSAxzaEUCXZ/avg1/OU5B14730QexIwNdL8Rm+PMNbuyPLQNl/blg8CCbLjgEiJBebGSi+STyFLEBVQtl3tfvgycswSZ8RELXdXk6mDkIGlSCO9x6Cq0minuOdRy3bnVJ3xpfbZ7l6vJpQ0YeulV+lf40FtP5o5RWwRmXt/wiQgj3PoRioklx2lMWrryt2oWSTjukYdDX9qPhimv+YsmLi797IyoRJITg3FxlXwU9cZSPSC107V1gxiNQcuUAn9GCtL5KstPz86Dk9bJlCNHjxK4TDd4e7fw8U4i0PBAEBIF8RK39a6cMfvLxjRFkwBxrGqvP3i2I+tj+6DhdY5oYbz5vad6mATbAen/znS0xcDdBn57WXTMM1fKSPZvj+o86wr+0OGPMHs3syz3Vo0o3ms4E1HhxVLDDLjKCqcc1XszHPde7FCxUY+ue0ayRLsRMrzaSCOuClIgA6S3iQHg2x35S9W3qXccAuHkPxY1VDYnN759mqmXb4Dp9/FGAKUZASt5HQ7y9tb5aLtm5WiiiZvzLF+hnCJpG5XW+YANzW/9IB/GgkYocxxkBf5+ZO2zog3AqKu1hYSyM7HtRRFnB56g=
addons:
  apt:
    packages:
    - libxml2-dev
    - libcurl4-gnutls-dev
    - libxml2-dev
    - libssl-dev
    - libopenblas-base
    - libcairo2-dev
    - libx11-xcb-dev
    - libxt-dev
    - libx11-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - netcdf-bin
r_packages:
- readxl
- ggplot2
- devtools
- dplyr
- tidyr
- readr
- shiny
- cluster
- proxy
- sca
- vegan
- GPArotation
- psych
r_github_packages:
- rstudio/bookdown
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
