language: r
sudo: required
dist: trusty
env:
  global:
  - secure: moJbCQgxX7vVMqD3JoaKXoFnFSdL4MetOR+4OT4kKB3OqYDdBxSmFa3R4VWO+K7+2dHWBKEAig3ymF1WUbzL2XO42/dDylzPGhzNrZioLi/XybWYSSL5VPrFlQQF6KAlT9GQvYysIDvRQsXses4mA6j7TnvMxTpC4TTGSW77fILENudCpjKtG3udLZZyXNcrlgg4lYzQFMtWsJzBI1UtMAQmZBegu7rvNbNmtwTnxmCvLYODYmVu2xKh5GeXiXgoJbSYDPQIHussbxrFobjxDHrTw6bn98/dVFIBepScLk3Yma67H8une1fqAy2nNHmK8v/pcR+5j4dTOkoMsCsPnnGCzUwo17JAtsr5VYtP9J0/+dZE6z9Xa9YwHMOsqE7CtIUd3wyX7598eLSYxYsFRqsrX4J/VcY8HyZVo/+cAboVKLCsYHqn6g65NLMtMw4S+YvSnl5tOR+jr91UgLutFv0y0swBIgCYRQmIq7pBaPjlG6ftAnjoAu5MammaZlWXlM15o3XjrgqjPTPPCSklcYAWRF/rfMfa0a8zy/h+yQapvcUdDmZy5l6tDKfWrOfQgeJIaQfvarpzVKhiR/yBGG6m87QYmi2joGK8OnI0qCC/igxMR02dk3Y8VGYDQ86K++fSuLM4+EW4MKDskJfZEN7Ahk2oAd573xkaxw9ip8Q=

addons:
  apt:
    packages:
    - libxml2-dev
    - libcurl4-gnutls-dev
    - libxml2-dev
    - libssl-dev
    - libopenblas-base
    - libcairo2-dev
    - libx11-xcb-dev
    - libxt-dev
    - libx11-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - netcdf-bin
r_packages:
- readxl
- ggplot2
- devtools
- dplyr
- tidyr
- readr
- shiny
- cluster
- proxy
- sca
- vegan
- GPArotation
- psych
r_github_packages:
- rstudio/bookdown
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
cache:
  packages: false
  directories:
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
