language: r
sudo: required
dist: trusty

env:
  global:
    secure: T9RKlD12mW0T73K0ZXEuwYTIKDpfsp7rSvt2sJqSZH8BnZwjwO2qkF2PXptTjDDODAOxx3FbkKi5TJn0PJOnh9xty975ahccnflMgnOm78gqlYUWHGwwQiBS3Z2E2eLCdOgzh4MBSDK1dU3jRfWKmlqhxBEtMspf54xgUY9BH3kQDIhzzhn8iNBV1SW7VBqAw3vnszTI/ItFp0rUPC1RKk7Uk305zkdUw8a6fu7+NEludFxLzLJfiUVMbmTtNOpBrdP5jKpeb0rLtQJwRQGJlkLKadQrOjW3ychHr4+oCUfzIV+77yyNyNKmrKd4EY/3rhLKUUl9Bjs5szX625p7zonNx4dnkUOvj7xroBm1QbZ0QEb11tZkULtKA+3VhIDvwA36vKZIE7v9o+kfEwpGcNYHGJqOWSiiL4aREtbf3Al6V2p03BnU1qb+bP1C5EWoXBfCXK5jYuHs6OxAjSxyRN7C1fnBmFZ2HYxwxc0wiN+IugLOHuIIyJjX3S8AGfGlfTsCGkgh1xBTk0STqIWmJSH5u5VrFqIplhwwutVg0VBFNF7dtQIatzjJfWceKIqlW+Z0rNRYXiXskXAwXvxxyXPJ34pgftgYZyqnbdcQL5vJ4J+7MFGle3J5pQzcZl4qKIfGt/8qGwvHooUAomiUBKnwUmmy6p+V9auhEnHvp5U=

addons:
  apt:
    packages:
      - libxml2-dev
      - libcurl4-gnutls-dev
      - libxml2-dev
      - libssl-dev
      - libopenblas-base
      - libcairo2-dev
      - libx11-xcb-dev
      - libxt-dev
      - libx11-dev
      - mesa-common-dev
      - libglu1-mesa-dev
      - netcdf-bin

r_packages:
  - readxl
  - ggplot2
  - devtools
  - dplyr
  - tidyr
  - readr
  - shiny
  - cluster
  - proxy
  - sca
  - vegan
  - GPArotation
  - psych

r_github_packages:
  - rstudio/bookdown

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

cache:
  packages: false
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
