--- 
title: "Introdução à Análise Multivariada usando R"
author: "Marcio Nicolau"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: marcionicolau/r-intro-multivar
download: ["pdf", "epub"]
description: "Este é o material base para o curso introdutório de Análise Multivariada utilizando o software R oferecido em Outubro/2016 na Embrapa Pesca e Aquicultura (Palmas/TO)"
---

# Pré-requisitos

Antes de iniciar o curso, faz-se nescessário instalar as ferramentas e pacotes para uso.

Será utilizado o sofware *`r R.Version()$version.string`* disponível em [CRAN](https://cran.r-project.org) e o *RStudio v1.0.44 Preview* disponível em [RStudio](https://www.rstudio.com/products/rstudio/download/preview/).

A carga horária total será de 20 horas (3 dias) nos quais os seguintes tópicos de Análise Multivariada serão abordados.

* Análise de Agrupamentos (CA)
* Análise de Componentes Principais (PCA)
* Análise Fatorial (FA)

Alguns exemplos serão realizados com dados disponíveis na literatura científica e, em certos momentos, serão utilizados dados dos próprios participantes.

Espera-se que ao final do curso o aluno seja capaz de entender o uso de cada técnica e aplicá-la de forma correta em seu campo/área de pesquisa.

Cabe lembrar que este é um curso introdutório e que de forma alguma os conteúdos e aplicações serão apresentadas de forma exaustiva.

Marcio Nicolau

Estatístico / Embrapa Trigo

Palmas/TO, Outubro de 2016

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
